- hosts: localhost
  gather_facts: no

  vars:
    tname: "{{ user }}_l1_target"
    hname: "{{ user }}_l1_host"
    port: "{{ cport }}:80"
    ops: "absent"

  tasks:
    - block:
        - name: boot ansible target container
          docker_container:
            name: "{{ tname }}"
            image: tksarah/lesson_ansible_target_pkged
            detach: true
            state: started
            ports:
              - "{{ port }}"

        - name: boot ansible host container
          docker_container:
            name: "{{ hname }}"
            image: "tksarah/lesson1_ansible_host"
            state: started
            volumes:
            - /root/ansible_lesson/roles/lesson1/files/_test:/mnt:ro
            command: "/bin/bash"
            links:
              - "{{ tname }}:web"
            tty: true
      tags: bootup

    - block:
        - name:  remove ansible target container
          docker_container:
            name: "{{ tname }}"
            image: tksarah/lesson_ansible_target_pkged
            state: "{{ ops }}"

        - name: remove ansible host container
          docker_container:
            name: "{{ hname }}"
            image: "tksarah/lesson1_ansible_host"
            state: "{{ ops }}"
      tags: remove
