- include_vars: userlist.yml
- include: users.yml
  vars:
    user: "{{ item.name }}"
    port: "{{ item.port }}"
  with_items:
    - "{{ group }}"

- include_vars: docker_var.yml
- include: rproxy.yml
