- name: Create proxy fiile
  shell: /{{ dockerfiledir }}/create_proxy.sh chdir={{ dockerfiledir }} creates=myproxy

- block:
    - name: Build rproxy image
      docker_image: path="{{ dockerfiledir }}/" name="tksarah/rproxy" state=build

    - name: Run Reverse Proxy on my container
      docker:
        name: "rproxy"
        image: tksarah/rproxy
        detach: true
        state: started
        ports:
          - "80:80"
        tty: true
  tags: rproxy

- name: Clean up
  file: path="{{ dockerfiledir }}/{{ item }}" state=absent
  with_items:
    - myproxy
    - userlist
