- name: Create proxy fiile
  script: /tmp/dockerfile/create_proxy.sh creates=/tmp/dockerfile/myproxy

- block:
    - name: Build rproxy image
      docker_image: path="/tmp/dockerfile" name="tksarah/rproxy" state=present force=true

    - name: Run Reverse Proxy on my container
      docker:
        name: "rproxy"
        image: tksarah/rproxy
        detach: true
        state: reloaded
        ports:
          - "80:80"
        tty: true
  tags: rproxy

- name: Clean up
  file: path="/tmp/dockerfile" state=absent
